apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  name: test-cluster
  namespace: postgres-operator-1
spec:
  image: percona/percona-postgresql-operator:2.3.1-ppg16-postgres
  imagePullPolicy: Always
  postgresVersion: 16
  instances:
  - name: instance1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
